'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';

interface Payment {
  id: string;
  amount: number;
  paymentMethod: string;
  createdAt: string;
}

interface Invoice {
  id: string;
  patient: {
    firstName: string;
    lastName: string;
    contactNo: string;
    address: string;
  };
  totalAmount: number;
  paidAmount: number;
  balanceAmount: number;
  status: string;
  items: any[];
  payments: Payment[];
  createdBy: {
    firstName: string;
    lastName: string;
  };
  createdAt: string;
}

export default function InvoiceDetailPage() {
  const { id } = useParams();
  const router = useRouter();
  const [invoice, setInvoice] = useState<Invoice | null>(null);
  const [loading, setLoading] = useState(true);
  const [paymentAmount, setPaymentAmount] = useState('');
  const [paymentMethod, setPaymentMethod] = useState('CASH');

  useEffect(() => {
    fetchInvoice();
  }, [id]);

  const fetchInvoice = async () => {
    try {
      const response = await fetch(`http://localhost:5000/api/billing/${id}`, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        }
      });
      const data = await response.json();
      setInvoice(data);
    } catch (error) {
      console.error('Error fetching invoice:', error);
    } finally {
      setLoading(false);
    }
  };

  const handlePayment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!invoice) return;

    try {
      const response = await fetch('http://localhost:5000/api/billing/payment', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        body: JSON.stringify({
          invoiceId: invoice.id,
          patientId: invoice.patient.id, // Wait, I need to make sure invoice has patient.id
          amount: parseFloat(paymentAmount),
          paymentMethod
        })
      });

      if (response.ok) {
        alert('Payment recorded successfully');
        setPaymentAmount('');
        fetchInvoice();
      } else {
        const data = await response.json();
        alert(data.message || 'Error recording payment');
      }
    } catch (error) {
      console.error('Payment Error:', error);
    }
  };

  if (loading) return <div className="p-6">Loading...</div>;
  if (!invoice) return <div className="p-6">Invoice not found.</div>;

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex justify-between items-center mb-6 no-print">
        <button onClick={() => router.back()} className="text-blue-600 hover:underline">
          ← Back to Invoices
        </button>
        <button 
          onClick={() => window.print()} 
          className="bg-gray-800 text-white px-4 py-2 rounded-lg hover:bg-gray-900 transition flex items-center gap-2"
        >
          🖨️ Print Receipt
        </button>
      </div>

      <div id="invoice-content" className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden mb-8 print:shadow-none print:border-none">
        <div className="p-8 border-b border-gray-100 flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">INVOICE</h1>
            <p className="text-gray-500">#{invoice.id.substring(0, 8)}</p>
          </div>
          <div className="text-right">
            <span className={`px-3 py-1 rounded-full text-sm font-semibold ${
              invoice.status === 'PAID' ? 'bg-green-100 text-green-800' : 
              invoice.status === 'PARTIALLY_PAID' ? 'bg-yellow-100 text-yellow-800' : 
              'bg-red-100 text-red-800'
            }`}>
              {invoice.status}
            </span>
            <p className="mt-4 text-sm text-gray-600">Date: {new Date(invoice.createdAt).toLocaleDateString()}</p>
          </div>
        </div>

        <div className="p-8 grid grid-cols-2 gap-8">
          <div>
            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Billed To</h3>
            <p className="text-lg font-bold text-gray-900">{invoice.patient.firstName} {invoice.patient.lastName}</p>
            <p className="text-gray-600">{invoice.patient.contactNo}</p>
            <p className="text-gray-600">{invoice.patient.address}</p>
          </div>
          <div className="text-right">
            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Generated By</h3>
            <p className="text-gray-900 font-medium">{invoice.createdBy.firstName} {invoice.createdBy.lastName}</p>
          </div>
        </div>

        <div className="px-8 pb-8">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="py-3 text-left text-xs font-bold text-gray-500 uppercase">Description</th>
                <th className="py-3 text-center text-xs font-bold text-gray-500 uppercase">Qty</th>
                <th className="py-3 text-right text-xs font-bold text-gray-500 uppercase">Unit Price</th>
                <th className="py-3 text-right text-xs font-bold text-gray-500 uppercase">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {Array.isArray(invoice.items) && invoice.items.map((item: any, idx: number) => (
                <tr key={idx}>
                  <td className="py-4 text-sm text-gray-900">{item.description}</td>
                  <td className="py-4 text-sm text-gray-900 text-center">{item.quantity}</td>
                  <td className="py-4 text-sm text-gray-900 text-right">${item.unitPrice.toFixed(2)}</td>
                  <td className="py-4 text-sm font-medium text-gray-900 text-right">${item.amount.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="mt-8 border-t border-gray-100 pt-8 flex justify-end">
            <div className="w-64 space-y-3">
              <div className="flex justify-between text-gray-600">
                <span>Total Amount</span>
                <span className="font-medium">${invoice.totalAmount.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-green-600">
                <span>Paid Amount</span>
                <span className="font-medium">-${invoice.paidAmount.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-xl font-bold text-gray-900 border-t border-gray-100 pt-3">
                <span>Balance</span>
                <span>${invoice.balanceAmount.toFixed(2)}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {invoice.status !== 'PAID' && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-8">
          <h2 className="text-xl font-bold text-gray-900 mb-6">Record Payment</h2>
          <form onSubmit={handlePayment} className="grid grid-cols-3 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Amount</label>
              <input
                type="number"
                step="0.01"
                required
                max={invoice.balanceAmount}
                value={paymentAmount}
                onChange={(e) => setPaymentAmount(e.target.value)}
                className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
                placeholder="0.00"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Method</label>
              <select
                value={paymentMethod}
                onChange={(e) => setPaymentMethod(e.target.value)}
                className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
              >
                <option value="CASH">Cash</option>
                <option value="CARD">Card</option>
                <option value="UPI">UPI</option>
                <option value="INSURANCE">Insurance</option>
              </select>
            </div>
            <div className="flex items-end">
              <button
                type="submit"
                className="w-full bg-green-600 text-white py-2 rounded-lg font-bold hover:bg-green-700 transition"
              >
                Confirm Payment
              </button>
            </div>
          </form>
        </div>
      )}

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="px-8 py-5 border-b border-gray-100">
          <h2 className="text-xl font-bold text-gray-900">Payment History</h2>
        </div>
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-8 py-3 text-left text-xs font-bold text-gray-500 uppercase">Date</th>
              <th className="px-8 py-3 text-left text-xs font-bold text-gray-500 uppercase">Method</th>
              <th className="px-8 py-3 text-right text-xs font-bold text-gray-500 uppercase">Amount</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {invoice.payments.length === 0 ? (
              <tr>
                <td colSpan={3} className="px-8 py-4 text-center text-gray-500 text-sm">No payments recorded yet.</td>
              </tr>
            ) : invoice.payments.map((payment) => (
              <tr key={payment.id}>
                <td className="px-8 py-4 text-sm text-gray-900">{new Date(payment.createdAt).toLocaleDateString()}</td>
                <td className="px-8 py-4 text-sm text-gray-900">{payment.paymentMethod}</td>
                <td className="px-8 py-4 text-sm font-medium text-gray-900 text-right">${payment.amount.toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
